import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional

try:
    import chromadb
    from chromadb.config import Settings
    CHROMA_AVAILABLE = True
except ImportError:
    CHROMA_AVAILABLE = False

try:
    from sentence_transformers import SentenceTransformer
    from PIL import Image
    SENTENCE_TRANSFORMERS_AVAILABLE = True
except ImportError:
    SENTENCE_TRANSFORMERS_AVAILABLE = False


BASE_DIR = Path(__file__).resolve().parent
CHROMA_DB_DIR = BASE_DIR / "chroma_db"

# Path open for the images generated by the pipeline
DEFAULT_IMAGES_DIR = BASE_DIR / "data_pipeline" / "unified_images"
DEFAULT_LABELS_FILE = BASE_DIR / "data_pipeline" / "unified_labels.json"

# Path open for the HuggingFace training datasets
DEFAULT_HF_DATASET_PATH = BASE_DIR.parent / "data" / "medical_train.jsonl"


class CustomRAG:
    def __init__(self, db_path: str = str(CHROMA_DB_DIR)):
        self.db_path = db_path
        self.image_collection_name = "medical_images_siglip"
        self.text_collection_name = "medical_text_pubmedbert"
        
        if CHROMA_AVAILABLE:
            # Initialize local persistent vector store
            self.chroma_client = chromadb.PersistentClient(path=self.db_path)
            
            # Collection for Images (using SigLIP space)
            self.image_collection = self.chroma_client.get_or_create_collection(
                name=self.image_collection_name,
                metadata={"hnsw:space": "cosine"}
            )
            
            # Collection for Medical Text (using PubMedBERT space)
            self.text_collection = self.chroma_client.get_or_create_collection(
                name=self.text_collection_name,
                metadata={"hnsw:space": "cosine"}
            )
        else:
            self.chroma_client = None
            self.image_collection = None
            self.text_collection = None
            print("WARNING: chromadb is not installed. RAG will not function.")

        # --- TWO TOWER ARCHITECTURE ---
        if SENTENCE_TRANSFORMERS_AVAILABLE:
            print("Loading Two-Tower Embedding Models...")
            print("1. Loading SigLIP for Multimodal (Images/Text)...")
            # SigLIP: Highly optimized multimodal model for aligning images to text queries.
            # Much smarter than original CLIP, runs perfectly on Snapdragon CPU/NPU.
            self.image_model = SentenceTransformer('nomic-ai/nomic-embed-vision-v1.5', trust_remote_code=True)
            # Falling back to standard SigLIP as it is more stable in sentence-transformers
            self.image_model = SentenceTransformer('google/siglip-base-patch16-224')

            print("2. Loading PubMedBERT for Clinical Text...")
            # PubMedBERT: Tiny but incredibly accurate for medical terminology.
            self.text_model = SentenceTransformer('pritamdeka/S-PubMedBert-MS-MARCO')
            print("Models loaded successfully.")
        else:
            self.image_model = None
            self.text_model = None
            print("WARNING: sentence-transformers or PIL not installed. Embeddings cannot be generated.")

    # --- TEXT (PubMedBERT) Tower ---
    def embed_medical_text(self, text: str) -> List[float]:
        if not self.text_model: return []
        return self.text_model.encode(text).tolist()

    # --- IMAGE/MULTIMODAL (SigLIP) Tower ---
    def embed_multimodal_text(self, text: str) -> List[float]:
        """Embed text using the image model to search the image database."""
        if not self.image_model: return []
        return self.image_model.encode(text).tolist()

    def embed_image(self, image_path: str) -> List[float]:
        if not self.image_model: return []
        image = Image.open(image_path)
        return self.image_model.encode(image).tolist()

    # --- INGESTION ---
    def ingest_images(self, images_dir: Path = DEFAULT_IMAGES_DIR, labels_file: Path = DEFAULT_LABELS_FILE):
        """
        Embed and store images from the data pipeline into the Image Collection using SigLIP.
        """
        if not self.image_collection or not self.image_model:
            print("Image RAG components missing. Cannot ingest.")
            return

        print(f"Ingesting images from {images_dir} using SigLIP...")
        if not labels_file.exists():
            print(f"Labels file {labels_file} not found. Run pipeline.py first.")
            return

        with open(labels_file, "r") as f:
            records = json.load(f)

        docs = []
        metadatas = []
        ids = []
        embeddings = []

        for i, record in enumerate(records):
            img_filename = Path(record['image_path']).name
            full_img_path = images_dir / img_filename

            if not full_img_path.exists():
                print(f"Warning: Image {full_img_path} not found.")
                continue

            try:
                emb = self.embed_image(str(full_img_path))
                
                embeddings.append(emb)
                docs.append(record.get('condition_label', 'Unknown Condition'))
                metadatas.append({
                    "source": record.get('source', 'unknown'),
                    "type": "image",
                    "image_path": str(full_img_path.resolve())
                })
                ids.append(f"img_{i}_{img_filename}")
                
                if len(embeddings) >= 50: # Batch insert
                    self.image_collection.add(
                        embeddings=embeddings,
                        documents=docs,
                        metadatas=metadatas,
                        ids=ids
                    )
                    embeddings, docs, metadatas, ids = [], [], [], []
                    print(f"Inserted image batch up to index {i}")
                    
            except Exception as e:
                print(f"Failed to embed {full_img_path}: {e}")

        # Insert remainder
        if embeddings:
            self.image_collection.add(
                embeddings=embeddings,
                documents=docs,
                metadatas=metadatas,
                ids=ids
            )
        print("Image ingestion complete.")

    def ingest_hf_datasets(self, dataset_path: Path = DEFAULT_HF_DATASET_PATH):
        """
        Embed and store text data from HuggingFace into the Text Collection using PubMedBERT.
        """
        if not self.text_collection or not self.text_model:
            print("Text RAG components missing. Cannot ingest.")
            return

        print(f"Ingesting HF datasets from {dataset_path} using PubMedBERT...")
        if not dataset_path.exists():
            print(f"Dataset path {dataset_path} not found.")
            return

        docs = []
        metadatas = []
        ids = []
        embeddings = []

        with open(dataset_path, "r") as f:
            for i, line in enumerate(f):
                if not line.strip(): continue
                
                try:
                    record = json.loads(line)
                    # We embed the JSON text, prioritizing explicit text fields
                    content = record.get('text', str(record))
                    
                    emb = self.embed_medical_text(content)
                    
                    embeddings.append(emb)
                    docs.append(content)
                    metadatas.append({
                        "source": "hf_medical_train",
                        "type": "text"
                    })
                    ids.append(f"text_hf_{i}")
                    
                    if len(embeddings) >= 50:
                        self.text_collection.add(
                            embeddings=embeddings,
                            documents=docs,
                            metadatas=metadatas,
                            ids=ids
                        )
                        embeddings, docs, metadatas, ids = [], [], [], []
                        print(f"Inserted HF text batch up to index {i}")
                        
                except Exception as e:
                    print(f"Failed to process line {i}: {e}")

        if embeddings:
            self.text_collection.add(
                embeddings=embeddings,
                documents=docs,
                metadatas=metadatas,
                ids=ids
            )
        print("HF dataset ingestion complete.")

    # --- RETRIEVAL ---
    def retrieve_text(self, query_text: str, n_results: int = 3):
        """Search the Medical Text database using PubMedBERT."""
        if not self.text_collection: return None
        query_embedding = self.embed_medical_text(query_text)
        return self.text_collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )

    def retrieve_images(self, query_text: str = None, query_image_path: str = None, n_results: int = 2):
        """Search the Image database using SigLIP (can search via text description or another image)."""
        if not self.image_collection: return None
        
        query_embeddings = []
        if query_text:
            query_embeddings.append(self.embed_multimodal_text(query_text))
        elif query_image_path:
            query_embeddings.append(self.embed_image(query_image_path))
        else:
            return {"error": "Must provide query_text or query_image_path"}

        return self.image_collection.query(
            query_embeddings=query_embeddings,
            n_results=n_results
        )

    def retrieve_hybrid(self, query_text: str, n_text: int = 2, n_images: int = 1):
        """
        The Two-Tower Master Query: Searches BOTH databases simultaneously
        using the correct embedding model for each.
        """
        text_results = self.retrieve_text(query_text, n_results=n_text)
        image_results = self.retrieve_images(query_text=query_text, n_results=n_images)
        
        return {
            "text_facts": text_results,
            "reference_images": image_results
        }

# Singleton instance for the FastAPI app
rag_service = CustomRAG()

if __name__ == "__main__":
    # Script entry point to pre-compute the database on the 5070Ti
    import argparse
    parser = argparse.ArgumentParser(description="Pre-compute Two-Tower RAG embeddings")
    parser.add_argument("--ingest-images", action="store_true", help="Ingest images using SigLIP")
    parser.add_argument("--ingest-hf", action="store_true", help="Ingest HF text using PubMedBERT")
    args = parser.parse_args()

    rag = CustomRAG()
    if args.ingest_images:
        rag.ingest_images()
    if args.ingest_hf:
        rag.ingest_hf_datasets()
    
    if not args.ingest_images and not args.ingest_hf:
        print("Run with --ingest-images or --ingest-hf to populate the local ChromaDB database.")
